name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks you for your interest in our project, we will do our best to address you issue as quickly as possible'' first issue'
        pr-message: 'Thank you for the help'' first pr'
